import type { TimeSlotConfig } from './timeSlots.js';

export const DEFAULT_TIME_SLOTS: TimeSlotConfig[] = [
  {
    id: 'slot-morning',
    milestoneId: 'system:day-startup',
    title: 'Day Startup Plan',
    time: '06:00',
    startHour: 6,
    startMinute: 0,
    endHour: 12,
    endMinute: 0,
  },
  {
    id: 'slot-midday',
    milestoneId: 'system:morning-summary',
    title: 'Morning Summary',
    time: '12:00',
    startHour: 12,
    startMinute: 0,
    endHour: 13,
    endMinute: 0,
  },
  {
    id: 'slot-afternoon',
    milestoneId: 'system:afternoon-startup',
    title: 'Afternoon Startup Plan',
    time: '13:00',
    startHour: 13,
    startMinute: 0,
    endHour: 17,
    endMinute: 0,
  },
  {
    id: 'slot-late-afternoon',
    milestoneId: 'system:afternoon-summary',
    title: 'Afternoon Summary',
    time: '17:00',
    startHour: 17,
    startMinute: 0,
    endHour: 19,
    endMinute: 0,
  },
  {
    id: 'slot-evening',
    milestoneId: 'system:evening-startup',
    title: 'Evening Startup',
    time: '19:00',
    startHour: 19,
    startMinute: 0,
    endHour: 21,
    endMinute: 30,
  },
  {
    id: 'slot-night',
    milestoneId: 'system:evening-summary',
    title: 'Evening Summary',
    time: '21:30',
    startHour: 21,
    startMinute: 30,
    endHour: 24,
    endMinute: 0,
  },
];
