name: UtralTodo
options:
  bundleIdPrefix: com.logat

targets:
  UtralTodo:
    type: application
    platform: iOS
    sources:
      - UtralTodo
    info:
      path: UtralTodo/Info.plist
      properties:
        UILaunchScreen:
          UILaunchScreen: {}
        UIBackgroundModes:
          - fetch
          - remote-notification
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleIconName: AppIcon
        CFBundleDisplayName: Utral Todo
    entitlements:
      path: UtralTodo/UtralTodo.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.logat.utralTodo
        aps-environment: development
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.logat.utralTodo
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.10"
        IPHONEOS_DEPLOYMENT_TARGET: 18.0
        DEVELOPMENT_TEAM: VW8PZV3Z69
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: UtralTodoWidget
        embed: true
      - package: UtralTodoKit

  UtralTodoWidget:
    type: app-extension
    platform: iOS
    sources:
      - UtralTodoWidget
    info:
      path: UtralTodoWidget/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
        CFBundleDisplayName: Utral Todo Widget
    entitlements:
      path: UtralTodoWidget/UtralTodoWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.logat.utralTodo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.logat.utralTodo.Widget
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.10"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        IPHONEOS_DEPLOYMENT_TARGET: 18.0
        DEVELOPMENT_TEAM: VW8PZV3Z69
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: UtralTodoKit

  UtralTodoWatch:
    type: application
    platform: watchOS
    sources:
      - path: ../iwatch/UtralTodoWatch
    dependencies:
      - package: UtralTodoKit
    info:
      path: ../iwatch/UtralTodoWatch/Info.plist
      properties:
        WKCompanionAppBundleIdentifier: com.logat.utralTodo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.logat.utralTodoWatch
        SWIFT_VERSION: "5.10"

packages:
  UtralTodoKit:
    path: UtralTodoKit
